### ISSUE TITLE
Reference not found for external definitions/refs

### ISSUE THREAD

**Issue by bkleef** [noahdietz/oatts#19] opened 2018-03-15 11:55 UTC
We include refs over HTTP (as described [here](https://swagger.io/docs/specification/using-ref/)).
Looks like `oatts` is unable to handle that:

```bash
+ oatts generate --host micro-api:8080 -s ./openapi/openapi.yaml --customValuesFile ./test/customValuesTest.json -m http -w ./test
Error: Reference not found: https://api-docs-profects-com.s3.dualstack.eu-central-1.amazonaws.com/openapi-refs/id.yaml#/definitions/ID
    at module.exports (/usr/local/share/.config/yarn/global/node_modules/deref/lib/util/find-reference.js:38:11)
    at copy (/usr/local/share/.config/yarn/global/node_modules/deref/lib/util/resolve-schema.js:16:19)
    at copy (/usr/local/share/.config/yarn/global/node_modules/deref/lib/util/resolve-schema.js:27:22)
    at copy (/usr/local/share/.config/yarn/global/node_modules/deref/lib/util/resolve-schema.js:27:22)
    at Object.module.exports [as resolveSchema] (/usr/local/share/.config/yarn/global/node_modules/deref/lib/util/resolve-schema.js:40:10)
    at $ref (/usr/local/share/.config/yarn/global/node_modules/deref/lib/index.js:63:14)
    at generate (/usr/local/share/.config/yarn/global/node_modules/json-schema-faker/lib/jsf.js:19:21)
    at Parameter.getSample (/usr/local/share/.config/yarn/global/node_modules/sway/lib/types/parameter.js:94:39)
    at /usr/local/share/.config/yarn/global/node_modules/oatts/lib/process.js:247:75
    at Array.forEach (<anonymous>)
+ mocha --recursive ./test
No test files found
```

Above error is based on [this `openapi.yaml` file](https://api-docs-agro4all-com.s3.dualstack.eu-central-1.amazonaws.com/mark-api/openapi.yaml). ReDoc can [handle it](https://api-docs-agro4all-com.s3.dualstack.eu-central-1.amazonaws.com/mark-api/index.html#).

Any ideas about how to fix this?

**Comment by noahdietz** [comment] 2018-05-06 03:15
Hi @bkleef sorry for the slow reply. Thanks for trying out `oatts`!

This might be a result of time and things have changed with your external references, but I am not able to reproduce this error. In fact, it seems `oatts` is able to resolve the refs over HTTP just fine. I actually get a different error in generating samples for params with `format: uuid`. If this is still an issue for you, lets figure it out. Otherwise, please close the issue.

On a side note, `oatts` is built on `sway`, which does all spec reference resolution and consumption. So if there is an issue with spec resolution, it would come from probably come from `sway`. Not shifting blame, just sharing context.

**Comment by phani1kumar** [comment] 2018-11-21 14:06
@noahdietz  thank you for your time in putting this together. I am facing similar issue, though it is able to get the referenced file, it is not able to generate the test cases!

```
Error: JSON Pointer points to missing location: #/paths/~1users~1{userId}~1lovedones~1{lovedoneId}/put/responses/200/schema/properties
    at /usr/local/share/.config/yarn/global/node_modules/json-refs/index.js:373:13
    at Array.forEach (<anonymous>)
    at findValue (/usr/local/share/.config/yarn/global/node_modules/json-refs/index.js:367:8)
    at setValue (/usr/local/share/.config/yarn/global/node_modules/json-refs/index.js:525:3)
    at /usr/local/share/.config/yarn/global/node_modules/json-refs/index.js:1242:15
    at Array.forEach (<anonymous>)
    at /usr/local/share/.config/yarn/global/node_modules/json-refs/index.js:1219:50
    at <anonymous>

```

**Comment by noahdietz** [comment] 2018-11-21 19:37
Hi thanks for adding onto this. This repo has been deprecated in favor of [google/oatts](https://github.com/google/oatts). Furthermore, the version of `sway` used here is a major version behind the favored repo, which might include some fixes. Please update your version of `oatts` or open a new issue on the active repo if the issue persists. Thanks

**Closed as completed by noahdietz** 2018-11-21 19:37 UTC
